Repository Recoded-Spark-Turkey-2022/The-Incredibles, pull requests merged in 2023-01, with the labels that each got.

#94 Display user blogs in MyAccount/Chiturca/issue86
  src/App.jsx
  src/app/store.js
  src/components/Navbar.jsx
  src/pages/UserProfile/MyAccount.jsx
  src/pages/UserProfile/MyAccountCard.jsx
  src/pages/UserProfile/MyAccountDetails.jsx
  src/pages/UserProfile/WriteBlog.jsx
Labels: enhancement

#127 Sync problem for Sign-up/Sign-in --Chiturca/issue125
  src/components/BlogCard/index.jsx
  src/pages/Signup/SignUp/index.jsx
  src/pages/Signup/SingIn/index.jsx
Labels: bug, documentation

#162 fix showing page name in mobile view
  src/components/Navbar/index.jsx
  src/pages/UserProfile/MyAccount/index.jsx
Labels: bug

#170 Style fix on blogs -- Chiturca/issue169
  src/assets/pics/blogpage/faceb.svg
  src/assets/pics/blogpage/insta.svg
  src/assets/pics/blogpage/searchIcon.svg
  src/assets/pics/blogpage/share.svg
  src/assets/pics/blogpage/tweter.svg
  src/assets/pics/profilepage/authorbg.svg
  src/components/BlogCard/index.jsx
  src/pages/Blogs/BlogDetails/index.jsx
  src/pages/Blogs/BlogsPage/index.jsx
Labels: bug
